// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilerOptions } from "./CompilerOptions";

export interface Config {
  globalScripts?: Array<string>;
  srcDir?: string;
  moduleDirs?: Array<string>;
  compilerOptions?: Array<CompilerOptions>;
}
