// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CompilerOptions {
  emit?: Array<string>;
  outDir?: string;
  importAssetsAsModule?: boolean;
  mainCssFileName?: string;
  useExactImports?: boolean;
  embedAssetMaxSize?: number;
  assetOutDir?: string;
  assetPrefix?: string;
  useAssetHashNames?: string;
}
