// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilerOptions } from "./CompilerOptions";
import type { LintConfig } from "./LintConfig";

export interface Config {
  experimental?: Array<string>;
  globalScripts?: Array<string>;
  lint?: LintConfig;
  srcDir?: string;
  designsDir?: string;
  moduleDirs?: Array<string>;
  compilerOptions?: Array<CompilerOptions>;
  openCodeEditorCommandTemplate?: string;
}
