/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "../../../../../styles/theme.pc.rs"]
mod theme;

#[derive(Properties, PartialEq)]
struct SelectableProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
fn Selectable(props: &SelectableProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Selectable-1f99a9f6-5", scope_class_name)
        } else {
            "_Selectable-1f99a9f6-5".to_string()
        }}>
            
        </div>
    }
}

