/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct FrameProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
    pub style: ,
}

#[function_component]
pub fn Frame(props: &FrameProps) -> Html {
    html! {
        <div style={props.style.clone()}>
            { for props.children.iter() }
        </div>
    }
}

