/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct TmpFooterProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
pub fn TmpFooter(props: &TmpFooterProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_TmpFooter-dc8bd3e8-7", scope_class_name)
        } else {
            "_TmpFooter-dc8bd3e8-7".to_string()
        }}>
            { for props.children.iter() }
        </div>
    }
}

