/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct CanvasProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
    pub onMouseMove: ,
    pub onScroll: ,
    pub onWheelCapture: ,
    pub style: ,
}

#[function_component]
pub fn Canvas(props: &CanvasProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Canvas-7b6f72e4-29", scope_class_name)
        } else {
            "_Canvas-7b6f72e4-29".to_string()
        }} onMouseMove={props.onMouseMove.clone()} onScroll={props.onScroll.clone()} onWheelCapture={props.onWheelCapture.clone()} style={props.style.clone()} tabIndex={"0"}>
            { for props.children.iter() }
        </div>
    }
}

#[derive(Properties, PartialEq)]
pub struct InnerProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
    pub class: String,
    pub style: ,
}

#[function_component]
pub fn Inner(props: &InnerProps) -> Html {
    html! {
        <div class={format!("{} {}", props.class.clone(), if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Inner-7b6f72e4-43", scope_class_name)
        } else {
            "_Inner-7b6f72e4-43".to_string()
        })} style={props.style.clone()}>
            { for props.children.iter() }
        </div>
    }
}

