/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct PixelsProps {
    pub __scope_class_name: Option<String>,
    pub style: ,
}

#[function_component]
pub fn Pixels(props: &PixelsProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Pixels-d2436674-25", scope_class_name)
        } else {
            "_Pixels-d2436674-25".to_string()
        }} style={props.style.clone()}></div>
    }
}

