/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "toolbar.pc.rs"]
mod toolbar;

#[derive(Properties, PartialEq)]
pub struct CenterPanelsProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn CenterPanels(props: &CenterPanelsProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_CenterPanels-bbee452d-12", scope_class_name)
        } else {
            "_CenterPanels-bbee452d-12".to_string()
        }}>
            <toolbar::Toolbar></toolbar::Toolbar>
            
        </div>
    }
}

