/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct ContextMenuProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn ContextMenu(props: &ContextMenuProps) -> Html {
    html! {
        <div></div>
    }
}

