/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[derive(Properties, PartialEq)]
pub struct ModalProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn Modal(props: &ModalProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Modal-70c647ed-8", scope_class_name)
        } else {
            "_Modal-70c647ed-8".to_string()
        }}></div>
    }
}

