/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "sidebar.pc.rs"]
mod sidebar;

#[path = "theme.pc.rs"]
mod theme;

#[path = "input.pc.rs"]
mod input;

#[path = "styles-panel.pc.rs"]
mod stylesPanel;

#[derive(Properties, PartialEq)]
pub struct RightSidebarProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
pub fn RightSidebar(props: &RightSidebarProps) -> Html {
    html! {
        <sidebar::Sidebar>
            { for props.children.iter() }
        </sidebar::Sidebar>
    }
}

#[derive(Properties, PartialEq)]
pub struct VariantPopupProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn VariantPopup(props: &VariantPopupProps) -> Html {
    html! {
        <sidebar::SidebarPopup header={
            
}>
            <sidebar::SidebarPopupPanelContent>
                <input::Fields>
                    <input::Field input={
                        <input::TextInput value={"something"}></input::TextInput>
                        
} name={
                        
}></input::Field>
                    
                    <input::Field input={
                        <input::TextInput value={"'.alt'"}></input::TextInput>
                        
} name={
                        
}></input::Field>
                    
                    <input::Field input={
                        <input::TextInput value={"':nth-child(2n)'"}></input::TextInput>
                        
}></input::Field>
                    
                    <input::Field input={
                        <input::TextInput value={"add..."}></input::TextInput>
                        
}></input::Field>
                    
                </input::Fields>
                
            </sidebar::SidebarPopupPanelContent>
            
        </sidebar::SidebarPopup>
    }
}

#[derive(Properties, PartialEq)]
pub struct PreviewProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn Preview(props: &PreviewProps) -> Html {
    html! {
        <RightSidebar>
            <stylesPanel::Preview></stylesPanel::Preview>
            
            <sidebar::SidebarPanel>
                <sidebar::SidebarSection>
                    <sidebar::SidebarPanelHeader>
                        
                        <div class={"_Preview-fa34a0f5-60"}></div>
                        
                    </sidebar::SidebarPanelHeader>
                    
                    <sidebar::SidebarPopupPanelContent>
                        <input::Fields>
                            <input::Field input={
                                <input::Select class={"error"} value={
                                    
}></input::Select>
                                
} name={
                                <input::Select value={
                                    
}></input::Select>
                                
}></input::Field>
                            
                            <input::Field input={
                                <input::Select value={
                                    
}></input::Select>
                                
} name={
                                <input::Select value={
                                    
}></input::Select>
                                
}></input::Field>
                            
                        </input::Fields>
                        
                    </sidebar::SidebarPopupPanelContent>
                    
                </sidebar::SidebarSection>
                
                <sidebar::SidebarSection>
                    <sidebar::SidebarPopupPanelContent>
                        <input::Fields>
                            <input::Field input={
                                <input::MultiSelect>
                                    
                                </input::MultiSelect>
                                
} name={
                                
}></input::Field>
                            
                            <input::Field input={
                                <input::TextInput value={"alt"}></input::TextInput>
                                
} name={
                                
                                <VariantPopup></VariantPopup>
                                
}></input::Field>
                            
                            <input::Field input={
                                <input::TextInput value={"add..."}></input::TextInput>
                                
}></input::Field>
                            
                        </input::Fields>
                        
                    </sidebar::SidebarPopupPanelContent>
                    
                </sidebar::SidebarSection>
                
            </sidebar::SidebarPanel>
            
        </RightSidebar>
    }
}

