/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "common.pc.rs"]
mod common;

#[path = "theme.pc.rs"]
mod theme;

#[path = "input.pc.rs"]
mod input;

#[derive(Properties, PartialEq)]
struct ColorPickerPopupProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
fn ColorPickerPopup(props: &ColorPickerPopupProps) -> Html {
    html! {
        <common::SidebarPopup header={
            
}>
            <common::SidebarPanelContent __scope_class_name={"_ColorPickerPopup-bdf7c0fc-25"}>
                <color-picker height={"130"} width={"220"}></color-picker>
                
                <div>
                    
                </div>
                
                <div>
                    
                </div>
                
                <div>
                    
                </div>
                
            </common::SidebarPanelContent>
            
            <common::SidebarPanelContent __scope_class_name={"_ColorPickerPopup-bdf7c0fc-52"}>
                <div>
                    
                </div>
                
                <div>
                    
                </div>
                
                <div>
                    
                </div>
                
            </common::SidebarPanelContent>
            
        </common::SidebarPopup>
    }
}

#[derive(Properties, PartialEq)]
pub struct PreviewProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn Preview(props: &PreviewProps) -> Html {
    html! {
        <common::SidebarPanel>
            <common::SidebarSection>
                <common::SidebarPanelContent>
                    <input::Field input={
                        <input::MultiSelect>
                            <input::MultiSelectItem>
                                
                            </input::MultiSelectItem>
                            
                            <input::MultiSelectItem>
                                
                            </input::MultiSelectItem>
                            
                        </input::MultiSelect>
                        
} name={
                        
}></input::Field>
                    
                </common::SidebarPanelContent>
                
            </common::SidebarSection>
            
            <common::SidebarSection>
                <common::SidebarPanelHeader>
                    
                    <div class={"_Preview-bdf7c0fc-73"}></div>
                    
                </common::SidebarPanelHeader>
                
                <common::SidebarPanelContent>
                    <input::Fields>
                        <input::Field input={
                            <input::Select value={
                                <input::Token class={"keyword"}>
                                    
                                </input::Token>
                                
}></input::Select>
                            
} name={
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::TextInput class={"active"} placeholder={"0px"} value={""}></input::TextInput>
                            
} name={
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::TextInput placeholder={"0px"} value={""}></input::TextInput>
                            
} name={
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::Select value={
                                <input::Token class={"keyword"}>
                                    
                                </input::Token>
                                
}></input::Select>
                            
} name={
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::Select value={
                                <input::Token class={"keyword"}>
                                    
                                </input::Token>
                                
}></input::Select>
                            
} name={
                            
}></input::Field>
                        
                    </input::Fields>
                    
                </common::SidebarPanelContent>
                
            </common::SidebarSection>
            
            <common::SidebarSection>
                <common::SidebarPanelHeader>
                    
                    <div class={"_Preview-bdf7c0fc-134"}></div>
                    
                </common::SidebarPanelHeader>
                
                <common::SidebarPanelContent>
                    <input::Fields>
                        <input::Field input={
                            <input::ColorInput>
                                <span>
                                    <input::Token class={"call"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"punc"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"number"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"punc"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"number"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"punc"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"number"}>
                                        
                                    </input::Token>
                                    
                                    <input::Token class={"punc"}>
                                        
                                    </input::Token>
                                    
                                </span>
                                
                            </input::ColorInput>
                            
} name={
                            
                            <ColorPickerPopup></ColorPickerPopup>
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::ColorInput>
                                <span>
                                    <input::Token class={"keyword"}>
                                        
                                    </input::Token>
                                    
                                </span>
                                
                            </input::ColorInput>
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::ColorInput>
                                <span>
                                    <input::Token class={"keyword"}>
                                        
                                    </input::Token>
                                    
                                </span>
                                
                            </input::ColorInput>
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::TextInput placeholder={"0px"} value={""}>
                                
                            </input::TextInput>
                            
} name={
                            
}></input::Field>
                        
                    </input::Fields>
                    
                </common::SidebarPanelContent>
                
            </common::SidebarSection>
            
            <common::SidebarSection>
                <common::SidebarPanelContent>
                    <input::Fields>
                        <input::Field input={
                            <input::Select value={
                                
}></input::Select>
                            
} name={
                            <div class={"_Preview-bdf7c0fc-241"}>
                                <div class={"_Preview-bdf7c0fc-239"}></div>
                                
                                
                            </div>
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::Select value={
                                
}></input::Select>
                            
}></input::Field>
                        
                        <input::Field input={
                            <input::Select value={
                                
}></input::Select>
                            
}></input::Field>
                        
                    </input::Fields>
                    
                </common::SidebarPanelContent>
                
            </common::SidebarSection>
            
            <div class={"_Preview-bdf7c0fc-298"}>
                <common::SidebarSection>
                    <common::SidebarPanelHeader>
                        
                        <div class={"_Preview-bdf7c0fc-272"}></div>
                        
                    </common::SidebarPanelHeader>
                    
                    <common::SidebarPanelContent>
                        <input::Fields>
                            <input::Field input={
                                <input::ColorInput>
                                    
                                </input::ColorInput>
                                
} name={
                                
}></input::Field>
                            
                            <input::Field input={
                                <input::TextInput value={"12px"}></input::TextInput>
                                
} name={
                                
}></input::Field>
                            
                        </input::Fields>
                        
                    </common::SidebarPanelContent>
                    
                </common::SidebarSection>
                
            </div>
            
        </common::SidebarPanel>
    }
}

