/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "theme.pc.rs"]
mod theme;

#[path = "common.pc.rs"]
mod common;

#[derive(Properties, PartialEq)]
struct ToolbarButtonProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
    pub class: ,
}

#[function_component]
fn ToolbarButton(props: &ToolbarButtonProps) -> Html {
    html! {
        <button class={format!("{} {}", props.class.clone(), if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_ToolbarButton-6cd1ddfb-39", scope_class_name)
        } else {
            "_ToolbarButton-6cd1ddfb-39".to_string()
        })}>
            { for props.children.iter() }
        </button>
    }
}

#[derive(Properties, PartialEq)]
struct ZoomProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
fn Zoom(props: &ZoomProps) -> Html {
    html! {
        <div>
            { for props.children.iter() }
        </div>
    }
}

#[derive(Properties, PartialEq)]
struct ToolbarDividerProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
fn ToolbarDivider(props: &ToolbarDividerProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_ToolbarDivider-6cd1ddfb-57", scope_class_name)
        } else {
            "_ToolbarDivider-6cd1ddfb-57".to_string()
        }}></div>
    }
}

#[derive(Properties, PartialEq)]
pub struct ToolbarProps {
    pub __scope_class_name: Option<String>,
}

#[function_component]
pub fn Toolbar(props: &ToolbarProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Toolbar-6cd1ddfb-128", scope_class_name)
        } else {
            "_Toolbar-6cd1ddfb-128".to_string()
        }}>
            <div class={"_Toolbar-6cd1ddfb-127"}>
                <ToolbarButton>
                    <div class={"_Toolbar-6cd1ddfb-89"}></div>
                    
                </ToolbarButton>
                
                <ToolbarButton>
                    <div class={"_Toolbar-6cd1ddfb-101"}></div>
                    
                </ToolbarButton>
                
                <ToolbarDivider></ToolbarDivider>
                
                <ToolbarButton>
                    <div class={"_Toolbar-6cd1ddfb-111"}></div>
                    
                </ToolbarButton>
                
                <ToolbarButton>
                    <div class={"_Toolbar-6cd1ddfb-120"}></div>
                    
                </ToolbarButton>
                
                <ToolbarDivider></ToolbarDivider>
                
                <ToolbarButton class={"wide"}>
                    
                </ToolbarButton>
                
            </div>
            
        </div>
    }
}

