/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "theme.pc.rs"]
mod theme;

#[derive(Properties, PartialEq)]
pub struct TreeNavigationItemProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
pub fn TreeNavigationItem(props: &TreeNavigationItemProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_TreeNavigationItem-8f4d0c55-15", scope_class_name)
        } else {
            "_TreeNavigationItem-8f4d0c55-15".to_string()
        }}>
            { for props.children.iter() }
        </div>
    }
}

#[derive(Properties, PartialEq)]
pub struct TreeNavigationItemHeaderProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
pub fn TreeNavigationItemHeader(props: &TreeNavigationItemHeaderProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_TreeNavigationItemHeader-container-8f4d0c55-42", scope_class_name)
        } else {
            "_TreeNavigationItemHeader-container-8f4d0c55-42".to_string()
        }}>
            { for props.children.iter() }
        </div>
    }
}

#[derive(Properties, PartialEq)]
pub struct TreeNavigationItemContentProps {
    pub __scope_class_name: Option<String>,
    #[prop_or_default]
    pub children: Children,
}

#[function_component]
pub fn TreeNavigationItemContent(props: &TreeNavigationItemContentProps) -> Html {
    html! {
        <div>
            { for props.children.iter() }
        </div>
    }
}

