/**
 * !! This file is AUTO GENERATED by the Paperclip Yew compiler.
 */

use yew::prelude::*;
use yew::{function_component, Children, html, Properties, Callback, MouseEvent};

#[path = "../../../../../styles/theme.pc.rs"]
mod theme;

#[derive(Properties, PartialEq)]
pub struct KnobProps {
    pub __scope_class_name: Option<String>,
    pub class: ,
    pub onMouseDown: ,
    pub style: ,
}

#[function_component]
pub fn Knob(props: &KnobProps) -> Html {
    html! {
        <svg class={format!("{} {}", props.class.clone(), if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Knob-9e53e128-56", scope_class_name)
        } else {
            "_Knob-9e53e128-56".to_string()
        })} onMouseDown={props.onMouseDown.clone()} style={props.style.clone()}>
            <rect class={"_Knob-9e53e128-55"}></rect>
            
        </svg>
    }
}

#[derive(Properties, PartialEq)]
pub struct EdgeProps {
    pub __scope_class_name: Option<String>,
    pub class: String,
    pub onMouseDown: ,
}

#[function_component]
pub fn Edge(props: &EdgeProps) -> Html {
    html! {
        <div class={format!("{} {}", props.class.clone(), if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Edge-9e53e128-124", scope_class_name)
        } else {
            "_Edge-9e53e128-124".to_string()
        })} onMouseDown={props.onMouseDown.clone()}></div>
    }
}

#[derive(Properties, PartialEq)]
pub struct OverlayProps {
    pub __scope_class_name: Option<String>,
    pub edges: Children,
    pub knobs: Children,
    pub onClick: ,
    pub onMouseDown: ,
    pub size: Children,
    pub style: ,
}

#[function_component]
pub fn Overlay(props: &OverlayProps) -> Html {
    html! {
        <div class={if let Some(scope_class_name) = &props.__scope_class_name {
            format!("{} {}", "_Overlay-9e53e128-204", scope_class_name)
        } else {
            "_Overlay-9e53e128-204".to_string()
        }} onClick={props.onClick.clone()} onMouseDown={props.onMouseDown.clone()} style={props.style.clone()}>
            { for props.knobs.iter() }
            { for props.edges.iter() }
            <div class={"_Overlay-footer-9e53e128-203"}>
                { for props.size.iter() }
            </div>
            
        </div>
    }
}

